#include <stdio.h>
#include <limits.h>
#include <float.h>

// A sample structure
struct sampleStruct {
    int a;
    double b;
    char c;
};

// An enumeration type
enum week{Mon, Tue, Wed, Thu, Fri, Sat, Sun};

int main(void) {
    FILE *file = NULL;
    if (sizeof(long) == 4) file = fopen("ptc_solver_memory_model_ilp32.pl", "w");
    else file = fopen("ptc_solver_memory_model_ilp64.pl", "w");

    if(file == NULL) {
        printf("Unable to create file.\n");
        return 1;
    }
    fprintf(file, "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");
    fprintf(file, "%%Automatically generated by compiling 'gcc -m32|-m64 create_c_types_for_ptc_solver.c' and executing a.out\n");
    fprintf(file, "%%Should be generated on install\n");
    fprintf(file, "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n");

    fprintf(file, "c_type_declaration('char', 'integer', %lu, %d, %d).\n", (unsigned long)sizeof(char), CHAR_MIN, CHAR_MAX);
    fprintf(file, "c_type_declaration('unsigned(char), 'integer', %lu, 0, %u).\n", (unsigned long)sizeof(unsigned char), UCHAR_MAX);

    fprintf(file, "c_type_declaration('short', 'integer', %lu, %d, %d).\n", (unsigned long)sizeof(short), SHRT_MIN, SHRT_MAX);
    fprintf(file, "c_type_declaration('unsigned_short', 'integer', %lu, 0, %u).\n", (unsigned long)sizeof(unsigned short), USHRT_MAX);

    fprintf(file, "c_type_declaration('int', 'integer', %lu, %d, %d).\n", (unsigned long)sizeof(int), INT_MIN, INT_MAX);
    fprintf(file, "c_type_declaration('unsigned_int', 'integer', %lu, 0, %u).\n", (unsigned long)sizeof(unsigned int), UINT_MAX);

    fprintf(file, "c_type_declaration('long', 'integer', %lu, %ld, %ld).\n", (unsigned long)sizeof(long), LONG_MIN, LONG_MAX);
    fprintf(file, "c_type_declaration('unsigned_long', 'integer', %lu, 0, %lu).\n", (unsigned long)sizeof(unsigned long), ULONG_MAX);

    fprintf(file, "c_type_declaration('long_long', 'integer', %lu, %lld, %lld).\n", (unsigned long)sizeof(long long), LLONG_MIN, LLONG_MAX);
    fprintf(file, "c_type_declaration('unsigned_long_long', 'integer', %lu, 0, %llu).\n", (unsigned long)sizeof(unsigned long long), ULLONG_MAX);

    fprintf(file, "c_type_declaration('float', 'floating_point', %lu, %g, %g).\n", (unsigned long)sizeof(float), FLT_MIN, FLT_MAX);
    fprintf(file, "c_type_declaration('double', 'floating_point', %lu, %g, %g).\n", (unsigned long)sizeof(double), DBL_MIN, DBL_MAX);
    fprintf(file, "c_type_declaration('long_double', 'floating_point', %lu, %Lg, %Lg).\n", (unsigned long)sizeof(long double), LDBL_MIN, LDBL_MAX);

    fprintf(file, "c_type_declaration('pointer', 'integer', %lu, 'rubbish', 'rubbish').\n", (unsigned long)sizeof(void*));
    fprintf(file, "c_type_declaration('boolean', 'integer', %lu, 0, 1).\n", (unsigned long)sizeof(_Bool));

    fprintf(file, "c_type_declaration('enum', 'integer', %lu, %d, %d).\n", (unsigned long)sizeof(enum week), INT_MIN, INT_MAX);
    fprintf(file, "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%");

    fclose(file);
    printf("Default type declaration file written successfully.\n");
    return 0;
}