%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%Automatically generated by compiling 'gcc -m32|-m64 create_c_types_for_ptc_solver.c' and executing a.out
Should be generated on install
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%c_type_declaration('char', 'integer', 1, -128, 127).
c_type_declaration('unsigned(char), 'integer', 1, 0, 255).
c_type_declaration('short', 'integer', 2, -32768, 32767).
c_type_declaration('unsigned_short', 'integer', 2, 0, 65535).
c_type_declaration('int', 'integer', 4, -2147483648, 2147483647).
c_type_declaration('unsigned_int', 'integer', 4, 0, 4294967295).
c_type_declaration('long', 'integer', 8, -9223372036854775808, 9223372036854775807).
c_type_declaration('unsigned_long', 'integer', 8, 0, 18446744073709551615).
c_type_declaration('long_long', 'integer', 8, -9223372036854775808, 9223372036854775807).
c_type_declaration('unsigned_long_long', 'integer', 8, 0, 18446744073709551615).
c_type_declaration('float', 'floating_point', 4, 1.17549e-38, 3.40282e+38).
c_type_declaration('double', 'floating_point', 8, 2.22507e-308, 1.79769e+308).
c_type_declaration('long_double', 'floating_point', 16, 3.3621e-4932, 1.18973e+4932).
c_type_declaration('pointer', 'integer', 8, 'rubbish', 'rubbish').
c_type_declaration('boolean', 'integer', 1, 0, 1).
c_type_declaration('enum', 'integer', 4, -2147483648, 2147483647).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%